WeatherCheckerFrontend/ViewModels/WeatherViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace WeatherCheckerFrontend.ViewModels
{
    public class WeatherViewModel
    {
        public bool IsSucceeded { get; set; }

        public string Message { get; set; }

        public string City { get; set; }

        public string Country { get; set; }

        public string Temperature { get; set; }

        public string Humidity { get; set; }
    }
}

WeatherCheckerFrontend/Controllers/ErrorController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace WeatherCheckerFrontend.Controllers
{
    public class ErrorController : Controller
    {
        // GET: Error
        public ActionResult UnknownError()
        {
            return View();
        }

        public ActionResult NotFound()
        {
            return View();
        }
    }
}

WeatherCheckerFrontend/Controllers/WeatherController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net.Http;
using System.Runtime.Serialization.Formatters.Binary;
using System.Threading.Tasks;
using System.Web;
using System.Web.Helpers;
using System.Web.Mvc;
using WeatherCheckerFrontend.Infrastructure.DTOs;
using WeatherCheckerFrontend.Infrastructure.Exceptions;
using WeatherCheckerFrontend.Infrastructure.Mappers;
using WeatherCheckerFrontend.Services;
using WeatherCheckerFrontend.Services.Interfaces;
using WeatherCheckerFrontend.ViewModels;

namespace WeatherCheckerFrontend.Controllers
{
    public class WeatherController : Controller
    {
        private readonly IWeatherService _weatherService;

        public WeatherController()
        {
            _weatherService = new WeatherService();
        }

        public WeatherController(IWeatherService weatherService)
        {
            _weatherService = weatherService;
        }

        [HttpGet]
        public ActionResult Check()
        {
            return View();
        }

        public async Task<JsonResult> CheckWeather(string country, string city)
        {
            WeatherViewModel viewModel;

            try
            {
                viewModel = WeatherResultDtoToViewModelMapper
                    .Map(await _weatherService.GetWeather(country, city));
            }
            catch (OneOfParametersIsEmptyException)
            {
                viewModel =
                    WeatherResultDtoToViewModelMapper
                    .EmptyWeatherViewModelWithMessage("One of parameters is empty");
            }
            catch (WebApiInternalErrorException)
            {
                viewModel =
                    WeatherResultDtoToViewModelMapper.EmptyWeatherViewModelWithMessage(
                        "Server with weather is unvailable");
            }
            catch (InvalidParameters)
            {
                viewModel =
                    WeatherResultDtoToViewModelMapper.EmptyWeatherViewModelWithMessage(
                        "Invalid parameters in form");
            }

            return Json(new { WeatherResult = viewModel }, JsonRequestBehavior.AllowGet);
        }
    }
}

WeatherCheckerFrontend/Views/Shared/_Layout.cshtml
@using System.Web.Optimization

<!DOCTYPE html>

<html>

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>

    @Styles.Render("~/content/bootstrap",
    "~/content/layout")

    @Scripts.Render("~/bundles/jQuery",
        "~/bundles/Knockout",
        "~/bundles/bootstrap"
        )
</head>

<body>
    <div id="allContent">
        <div id="mainNavbar" class="navbar">
            <h2 id="navbarHeader">
                <a id="navbarHeaderLink" href="@Url.Action("Check", "Weather")">Weather checker</a>
            </h2>
        </div>
        <div class="container page">
            <div id="main">
                <div>
                    @RenderBody()
                </div>
            </div>
        </div>
    </div>
</body>

</html>

WeatherCheckerFrontend/Views/Weather/Check.cshtml
@using System.Web.Optimization

@Styles.Render("~/content/weather",
    "~/content/kendo")

@Scripts.Render("~/bundles/Weater/Check",
    "~/bundles/kendo")

@{
    ViewBag.Title = "Check";
}

<div id="main">
    <div id="weatherForm">
        <div class="form-block">
            <label for="countryInputField" class="form-label">Country</label>
            <input id="countryInputField" class="form-input form-control" type="text" data-bind="value: WeatherForm().Country, valueUpdate: 'afterkeydown'"/>
        </div>
        <div class="form-block">
            <label for="cityInputField" class="form-label">City</label>
            <input id="cityInputField" class="form-input form-control" type="text" data-bind="value: WeatherForm().City, valueUpdate: 'afterkeydown'"/>
        </div>
        <div id="loadingButtonBlock" class="form-block">
            <button id="weatherFormButton" data-bind="click: CheckWeather" class="btn btn-primary btn-lg submit_btn" type="button">Check Weather</button>
        </div>
        <div id="messageBlock" class="form-block">
            <h5 id="wariningLabel"><span data-bind="text: MessageWarining"></span> </h5>
        </div>
    </div>
    <div id="weatherResult">
        <h3>Country: <span data-bind="text: WeatherResult().Country"></span> </h3>
        <h3>City: <span data-bind="text: WeatherResult().City"></span> </h3>

        <ul id="progressBars">
            <li>
                <h4>Temperature (&deg C)</h4>
                <div class="weatherResultprogressBar" id="temperatureBar"></div>
            </li>
            <li>
                <h4>Humidity</h4>
                <div class="weatherResultprogressBar" id="humidityBar"></div>
            </li>
        </ul>
    </div>
</div>

<div class="modal" id="loadingModal" role="dialog">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-body">
                <div align="center">
                    Loading weather...
                </div>
            </div>
        </div>
    </div>
</div>

WeatherCheckerFrontend/Views/Weather/Index.cshtml
@{
    ViewBag.Title = "Index";
}

<h2>Weather Controller - Index</h2>